// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class RankingPage {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Image currentUserGravatar;
	
	protected System.Web.UI.WebControls.Label currentUserName;
	
	protected System.Web.UI.WebControls.Label currentUserScore;
	
	protected System.Web.UI.WebControls.Button btnShowHow;
	
	public new MasterPage Master {
		get {
			return ((MasterPage)(base.Master));
		}
	}
}
